experiment_name: spatial_memory_libero_spatial_C16_seed42_4gpu_5k
git_commit: bb02b05d48f3eb1135a618f00489557b81faf4c6
model_group: C16 / SpatialMemoryVLA
experiment_mode: spatial_memory
seed: 42
num_gpus: 4
per_device_batch_size: 8
gradient_accumulation_steps: 8
global_batch_size: 256
max_steps: 5000
learning_rate: 2.0e-05
action_dim: 7
future_action_window_size: 15
action_horizon: 16
memory_length: 16
use_spatial_forcing: true
use_spatial_memory: true
vision_backbone_trainable: true
llm_backbone_trainable: true
repeated_diffusion_steps: 4
precision: BF16
fsdp_strategy: fsdp-full-shard
dataset: libero_spatial_no_noops
initial_checkpoint: /media/SpatialMemoryVLA-c16/pretrained/memvla-libero-spatial/checkpoints/memvla-libero-spatial.pt
vggt_checkpoint: /media/SpatialMemoryVLA-c16/pretrained/VGGT-1B/model.pt
llama2_repository: /media/SpatialMemoryVLA-c16/pretrained/NousResearch-Llama-2-7b-hf
checkpoint_interval: 2000
checkpoint_steps:
- 2000
- 4000
- 5000
image_augmentation: true
action_model_type: DiT-L
dataloader_type: group
group_size: 16
shuffle_buffer_size: 128000
spatial_align_layer: 24
spatial_align_coefficient: 0.5
spatial_teacher_feature_layer: -1
spatial_teacher_dimension: 2048
gradient_checkpointing: true
reduce_in_full_precision: true
optimizer: AdamW
weight_decay: 0.0
max_grad_norm: 1.0
lr_scheduler: constant
warmup_ratio: 0.0
